apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-kube-action-gitops
  description: This is GitOps manifest for go-kube-action   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: go-kube-action
    janus-idp.io/tekton: go-kube-action 
    backstage.io/kubernetes-id: go-kube-action
    backstage.io/kubernetes-namespace: go-kube-action
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-kube-action
